exp_dir: experiments_vit
dataset_dir: dataset
ckpt_zoo_dir: checkpoints
# venv_path: venv/bin/activate  # If using a SLURM cluster, uncomment this line.

devices: 1
num_nodes: 1
num_workers: 5
strategy: ddp_find_unused_parameters_true

module: cvt2distilgpt2_mimic_cxr_chen_vit
definition: CvT2DistilGPT2MIMICXRChen

test_ckpt_path: /scratch/railabs/ld258/dataset/CXR/mimic/jpeg/cvt2distilgpt2/experiments_vit/mimic_cxr/train_mimic_cxr_chen_cvt2distilgpt2_vit/trial_0/epoch=10-step=186175-val_chen_cider=0.331478.ckpt

encoder_lr: 5e-5
decoder_lr: 5e-4
mbatch_size: 4
every_n_epochs: 1

monitor: 'val_chen_cider'
monitor_mode: 'max'
precision: 16
decoder_max_len: 128
num_test_beams: 4

enable_progress_bar: True
weights_summary: 'full'

early_stopping: True
patience: 10
min_delta: 1e-4
deterministic: False
