exp_dir: experiments_lavsen
dataset_dir: dataset
ckpt_zoo_dir: checkpoints

devices: 1
num_nodes: 1
num_workers: 5
strategy: ddp_find_unused_parameters_true

module: cvt2distilgpt2_mimic_cxr_chen
definition: CvT2DistilGPT2MIMICXRChen

test_ckpt_path: /scratch/railabs/ld258/dataset/CXR/mimic/jpeg/cvt2distilgpt2/experiments_lavsen/mimic_cxr/train_mimic_cxr_chen_cvt2distilgpt2/trial_0/epoch=11-step=101556-val_chen_cider=0.306059.ckpt

encoder_lr: 5e-5
decoder_lr: 5e-4
mbatch_size: 4
every_n_epochs: 1

monitor: 'val_chen_cider'
monitor_mode: 'max'
precision: 16
decoder_max_len: 128
num_test_beams: 4

enable_progress_bar: True
weights_summary: 'full'

early_stopping: True
patience: 10
min_delta: 1e-4
deterministic: False
